### PR TITLE
chore: mark as prerelease for now

### PR DESCRIPTION
**Pull request by ggreif**
Maybe we can publish it like this without causing waves.

### CODE REVIEW

**Comment by ggreif** [comment]
I just see that you have `vsce package --pre-release`. My patch is modelled after `viper-ide`, so this might be the old way to do it...

**Comment by rvanasa** [comment]
If I remember correctly, `viper-ide` actually reads the `package.json` file to determine whether the current version is a pre-release, so this would probably have no effect for us. I might need to double-check this though.

**Comment by ggreif** [comment]
Yeah, that can be, so feel free to close if it is BS.

**Comment by rvanasa** [comment]
Also, it looks like we can "unpublish" the extension and try again if the `--pre-release` flag doesn't work for some reason. Maybe we could wait to see what happens, and then try this as a backup plan?

**Pull request closed without merging**
