### PR TITLE
Update mops and call `mops sources` with `--no-install` flag

### PR DESCRIPTION
**Pull request by ZenVoich**
Sometimes errors may occur when a user runs`mops install` because ext calls `mops sources` which starts with `mops install`, so we get two concurrent install processes. With `--no-install` flag this problem should go away.

### CODE REVIEW

**Comment by rvanasa** [comment]
Thanks for the fix! How recently was the `--no-install` flag added to Mops? Since the extension uses an externally installed Mops version (rather than the version bundled with the extension), we could adjust the error message to encourage updating Mops if the command is unsuccessful.

**Comment by rvanasa** [comment]
Here is what I'm imagining (updating the error message slightly below the original code change):

```ts
throw new Error(
    `Error while finding Mops packages.\nMake sure the latest version of Mops is installed locally or globally (https://mops.one/docs/install).\n${err?.message || err}`,
);
```

**Comment by ZenVoich** [comment]
> How recently was the --no-install flag added to Mops? Since the extension uses an externally installed Mops version (rather than the version bundled with the extension), we could adjust the error message to encourage updating Mops if the command is unsuccessful.

In `0.45.0` a week ago. Maybe we should give it a time so fewer users encounter errors...



> Here is what I'm imagining (updating the error message slightly below the original code change):

> The CI error should be fixable by running npm install in case that saves you a bit of time.

Done

**Review by rvanasa — APPROVED** [review]
LGTM; let's revisit this in a few weeks.

**Comment by ZenVoich** [comment]
Added mops version check

**Comment by rvanasa** [comment]
I just got a chance to check back on this. Thanks for the update! The PR is set to auto-merge after fixing the conflicts in `package-lock.json`.

**Pull request merged**
